signal: ["sig"]
hidden_layers: [128,128]
dropout_p: 0.3
features: "wh_htt_llt"
classes: "wh_htt_llt"
tca: false
tca_order: 2
learning_rate: 0.0001
L2: 0.001
batch_size: 256
early_stopping_patience: 50
early_stopping_value: 0.1
one_hot_parametrization: False
date: "27_03_25_Medium"
