signal: ["sig"]
hidden_layers: [1000,1000]
dropout_p: 0.4
features: "wh_htt_ltt"
classes: "wh_htt_ltt"
tca: False
tca_order: 1
learning_rate: 0.0001
L2: 0.001
batch_size: 500
early_stopping_patience: 50
early_stopping_value: 0.1
one_hot_parametrization: False
date: "22_05_24"