# This is an example config containing information for the preselection

ntuple_path: "root://cmsxrootd-kit.gridka.de//store/user/nshadskiy/CROWN/ntuples/nmssm_08_2023_boostedtau_v9/CROWNRun"
friends: "fakefactors_v1"
era: "2018"
channel: "mt"
tree: "ntuple"

output_path: "/ceph/nshadskiy/nmssm_ml/10_2023_v2_boosted"

processes:
    HToTauTau:
        tau_gen_modes:
            - "all"
        samples:
            - "GluGluHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"

    HToBB:
        tau_gen_modes:
            - "all"
        samples:
            - "GluGluHToBB_M-125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "VBFHToBB_M-125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"

    DYjets:
        tau_gen_modes:
            - "L"
        samples:
            - "DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY1JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY2JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY3JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY4JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"

    diboson:
        tau_gen_modes:
            - "L"
        samples:
            - "ZZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X" 
            - "WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "WZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X"

    ttbar:
        tau_gen_modes:
            - "L"
        samples:
            - "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToHadronic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"

    ST:
        tau_gen_modes:
            - "L"
        samples:
            - "ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
    embedding:
        tau_gen_modes:
            - "all"
        samples:
            - "TauEmbedding-MuTauFinalState_Run2018A-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018B-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018C-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018D-UL2018"

    tau_fakes:
        tau_gen_modes:
            - "all"
        samples:
            - "SingleMuon_Run2018A-UL2018"
            - "SingleMuon_Run2018B-UL2018"
            - "SingleMuon_Run2018C-UL2018"
            - "SingleMuon_Run2018D-UL2018"

    XToYHTo2Tau2B:
        tau_gen_modes:
            - "all"
        samples:
            - "NMSSM_XToYHTo2Tau2B_MX-massX_MY-massY_TuneCP5_13TeV-madgraph-pythia8_RunIISummer20UL18NanoAODv9-106X"

    XToYHTo2B2Tau:
        tau_gen_modes:
            - "all"
        samples:
            - "NMSSM_XToYHTo2B2Tau_MX-massX_MY-massY_TuneCP5_13TeV-madgraph-pythia8_RunIISummer20UL18NanoAODv9-106X"

general_event_selection:
    had_tau_pt: "boosted_pt_2 > 40"
    had_tau_eta: "abs(boosted_eta_2) < 2.3"
    had_tau_decay_mode: "(boosted_tau_decaymode_2 == 0) || (boosted_tau_decaymode_2 == 1) || (boosted_tau_decaymode_2 == 10)"
    had_tau_id_anti_ele: "id_boostedtau_antiEle_VLoose_2 > 0.5"
    had_tau_id_anti_mu: "id_boostedtau_antiMu_Loose_2 > 0.5"
    lep_pt: "boosted_pt_1 > 55"
    single_trigger: "trg_single_mu50_boosted > 0.5"
    tau_pair_sign: "(boosted_q_1*boosted_q_2) < 0" 
    no_extra_lep: "(boosted_extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
    good_tautau_pair: "(boosted_deltaR_ditaupair<=0.8)"

special_event_selection:
    had_boostedtau_id_iso: ["id_boostedtau_iso_Loose_2 > 0.5", "id_boostedtau_iso_Loose_2 < 0.5"]
    good_bb_pair: "(((bpair_deltaR_boosted>=0) && (nbtag_boosted>=1) && (bpair_btag_value_2_boosted>=0.049) && (abs(bpair_eta_2_boosted)<=2.5)) || ((fj_Xbb_particleNet_XbbvsQCD_boosted>=0.4) && (abs(fj_Xbb_eta_boosted)<=2.5) && (fj_Xbb_pt_boosted>=200)))"

mc_weights:
    # general weights: string is passed directly as weight
    pileup: "puweight"
    lep_iso: "iso_wgt_mu_boosted_1"
    lep_id: "id_wgt_mu_boosted_1"
    had_tau_id_vs_ele: (boosted_gen_match_2==5) * ((id_boostedtau_antiEle_VLoose_2>0.5)*id_wgt_boostedtau_antiEle_VLoose_2 + (id_boostedtau_antiEle_VLoose_2<0.5)) + (boosted_gen_match_2!=5)
    had_tau_id_vs_mu: (boosted_gen_match_2==5) * ((id_boostedtau_antiMu_Loose_2>0.5)*id_wgt_boostedtau_antiMu_Loose_2 + (id_boostedtau_antiMu_Loose_2<0.5)) + (boosted_gen_match_2!=5)
    
    # special weights: these are not generally applied, e.g. only for a specific process or era
    # here the string is a needed information to apply the weight -> see corresponding functions
    generator: "stitching"
    lumi: ""
    Z_pt_reweighting: "ZPtMassReweightWeight"
    Top_pt_reweighting: "topPtReweightWeight"

emb_weights:
    # general weights (for embedding): string is passed directly as weight
    generator: "emb_genweight * emb_idsel_wgt_1 * emb_idsel_wgt_2 * emb_triggersel_wgt"
    lep_iso: "iso_wgt_mu_boosted_1"
    lep_id: "id_wgt_mu_boosted_1"

masses_X: [280, 450, 800, 1200, 2000, 4000]
masses_Y: [70, 125, 250, 500, 1000, 1600, 2800]
# masses_X: [280]
# masses_Y: [70]

output_feature:
    - "weight"
    - "massX"
    - "massY"
    - "njets_boosted"
    - "nbtag_boosted"
    - "boosted_pt_1"
    - "boosted_pt_2"
    - "boosted_eta_1"
    - "boosted_phi_1"
    - "boosted_eta_2"
    - "boosted_phi_2"
    - "boosted_deltaR_ditaupair"
    - "boosted_m_vis"
    - "boosted_m_fastmtt"
    - "boosted_pt_fastmtt"
    - "boosted_eta_fastmtt"
    - "boosted_phi_fastmtt"
    - "bpair_pt_1_boosted"
    - "bpair_eta_1_boosted"
    - "bpair_phi_1_boosted"
    - "bpair_pt_2_boosted"
    - "bpair_eta_2_boosted"
    - "bpair_phi_2_boosted"
    - "bpair_m_inv_boosted"
    - "bpair_deltaR_boosted"
    - "bpair_pt_dijet_boosted"
    - "fj_Xbb_pt_boosted"
    - "fj_Xbb_eta_boosted"
    - "fj_Xbb_phi_boosted"
    - "fj_Xbb_msoftdrop_boosted"
    - "fj_Xbb_nsubjettiness_2over1_boosted"
    - "met_boosted"
    - "metphi_boosted"
    - "boosted_mass_tautaubb"
    - "boosted_pt_tautaubb"